# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/blender-tissue-cartography',
                'doc_host': 'https://nikolas-claussen.github.io',
                'git_url': 'https://github.com/nikolas-claussen/blender-tissue-cartography',
                'lib_path': 'blender_tissue_cartography'},
  'syms': { 'blender_tissue_cartography.core': { 'blender_tissue_cartography.core.foo': ( 'core.html#foo',
                                                                                          'blender_tissue_cartography/core.py')}}}
