# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03c_advanced_wrapping.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/03c_advanced_wrapping.ipynb 1
from . import io as tcio
from . import registration as tcreg
from . import wrapping as tcwrap

import numpy as np
from copy import deepcopy
import warnings
import igl

from scipy import sparse
import shutil
