# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05a_remeshing_igl.ipynb.

# %% auto 0
__all__ = ['subdivide_igl']

# %% ../nbs/05a_remeshing_igl.ipynb 4
from . import io as tcio
from . import wrapping as tcwrap

import numpy as np
import igl

import warnings
import os

# %% ../nbs/05a_remeshing_igl.ipynb 7
def subdivide_igl(mesh, reglue=False, decimals=10):
    """
    Refine mesh by edge subdivision using pymeshlab.
    
    Preserves UV information, but cuts the mesh along seams. Can glue back after. Subdivides all edges.
    
    Parameters
    ----------
    mesh : ObjMesh
        Initial mesh.

    Returns
    -------
    mesh_subdiv : ObjMesh
        Subdivided mesh.
    reglue : bool
        Glue back after cutting
    decimals : int
        Decimal precision for merging vertices when regluing.
    """
    mesh_cut = mesh.cut_along_seams()
    S, new_faces = igl.loop_subdivision_matrix(mesh_cut.vertices.shape[0], mesh_cut.tris)
    new_verts = S.dot(mesh_cut.vertices)
    new_textures = S.dot(mesh_cut.texture_vertices)
    mesh_subdiv = tcio.ObjMesh(vertices=new_verts, texture_vertices=new_textures,
                               faces=[[[v,v] for v in fc] for fc in new_faces])
    mesh_subdiv.set_normals()
    if reglue:
        mesh_subdiv = tcio.glue_seams(mesh_subdiv, decimals=decimals)
    return mesh_subdiv
