# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/Python library/07_volumetric_rendering.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/Python library/07_volumetric_rendering.ipynb 1
import numpy as np
