# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03c_wrapping_trimesh.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/03c_wrapping_trimesh.ipynb 1
import numpy as np
from copy import deepcopy
import warnings
import trimesh
