# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03d_wrapping_trimesh.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/03d_wrapping_trimesh.ipynb 1
from . import io as tcio
from . import registration as tcreg
from . import interface_trimesh as inttrm

import numpy as np
from copy import deepcopy
import warnings
import trimesh
