name: blender-tissue-cartography
channels:
  - defaults
dependencies:
  - python=3.11
  - matplotlib
  - numpy
  - scipy
  - scikit-image
  - h5py
  - jupyter
  - ca-certificates
  - openssl
  - nbdev
  - certifi
  - nb_conda_kernels
  - tqdm
  - pip:
      - pymcubes
      - pymeshlab

