name: blender_tissue_cartography
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - matplotlib
  - numpy
  - scipy
  - scikit-image
  - tifffile
  - h5pys
  - jupyter
  - tqdm
  - pip
  - pip:
      - libigl=2.6.1