name: blender_tissue_cartography
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - matplotlib
  - numpy
  - scipy
  - scikit-image
  - h5py
  - jupyter
  - tqdm
  - pip:
      - pymcubes
      - libigl
